"""Initial migration

Revision ID: 573ab9033e81
Revises: 
Create Date: 2026-01-12 17:56:29.096328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added missing import


# revision identifiers, used by Alembic.
revision: str = '573ab9033e81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('product',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('sku_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('product', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_product_sku_code'), ['sku_code'], unique=True)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('target_stock', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipment_date', sa.DateTime(), nullable=False),
    sa.Column('rma_ticket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment')
    op.drop_table('inventory')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku_code'))

    op.drop_table('product')
    # ### end Alembic commands ###
